spring.application.name=orbix-backend

# Use embedded H2 database by default
spring.datasource.url=jdbc:postgresql://ep-icy-recipe-an3mzea3-pooler.c-6.us-east-1.aws.neon.tech/ORBIXDB?sslmode=require&channel_binding=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_P7cMZBgAQ1kY


# Show SQL and let Hibernate create/drop schema in dev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable H2 console (http://localhost:8080/h2-console)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
